# this program runs whenever something is pushed onto the main branch
name: Sending Discord Message
on: 
  push: 
    branches: [main] 

jobs: 
  builds:
    runs-on: ubuntu-latest
    name: my second build
    steps:
     - name: Discord Message
       uses: discord-actions/message@v2
       with:
         webhookUrl: https://discord.com/api/webhooks/1316956354786885673/TnLUfOQiSbcjinGjEXP44tQwVosbe8HGv_gviHMyIZYWbWlr4rcTYRDpNk24h2DO7pa5
         message: "hello liqi is here" 
